### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by luizbon**
Jest 18 require return results

### CODE REVIEW

**Comment by adalbertoteixeira** [comment]
Hi @luizbon . I've updated to jest and it's working just fine in Bamboo.

**Comment by luizbon** [comment]
According to v18 changelog testResultsProcessor should return modified results, why not be compliant?
https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-1800

**Comment by luizbon** [comment]
Hi @adalbertoteixeira, sorry to insist, but I've started to get the following error:
```
TypeError: Cannot read property 'snapshot' of undefined
    at results (\node_modules\jest-cli\build\jest.js:338:41)
    at source.getTestPaths.then.then.then.runResults (\node_modules\jest-cli\build\jest.js:255:28)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
After a quick research found out that it happens when doing watch and had this issue related to it: https://github.com/facebook/jest/issues/2357
Since it is an external package which was causing and the error is about undefined object, I give another try with my branch code and the error went away.

It looks like this return does not break a standard test run, but when I'm using the watch argument, it starts to fail.

**Comment by adalbertoteixeira** [comment]
@luizbon, my issue here is that for us it's running fine in production and the tests in bamboo are passing just fine. Does this work for you when you running the tests in bamboo?

If it does I'll merge this.

**Comment by luizbon** [comment]
@adalbertoteixeira I did a test and it worked! 😃

**Pull request merged**
